
#include <iostream>
#include <string>
#include <vector>

using namespace std;

/*
https://leetcode.com/problems/find-the-difference/

Given two strings s and t which consist of only lowercase letters.

String t is generated by random shuffling string s and then add one more letter at a random position.

Find the letter that was added in t.

Example:

Input:
s = "abcd"
t = "abcde"

Output:
e

Explanation:
'e' is the letter that was added.

*/

// NAIVE
//Runtime: 8 ms, faster than 52.07% of C++ online submissions for Find the Difference.
//Memory Usage : 6.8 MB, less than 54.25% of C++ online submissions for Find the Difference.
//class Solution {
//public:
//
//	vector<int> BuildHist(const string& s)
//	{
//		vector<int> result(256, 0);
//		for (int i = 0; i < s.size(); ++i)
//			++result[s[i]];
//		return result;
//	}
//
//	char findTheDifference(string s, string t)
//	{
//		auto hist1 = BuildHist(s);
//		auto hist2 = BuildHist(t);
//		for (int c = 0; c < 256; ++c)
//		{
//			if (hist1[c] != hist2[c])
//				return c;
//		}
//		return 0;
//	}
//};

//Runtime: 4 ms, faster than 97.98% of C++ online submissions for Find the Difference.
//Memory Usage : 6.9 MB, less than 15.00% of C++ online submissions for Find the Difference.
class Solution {
public:

	char xorChars(const string& s) {
		char r = 0;
		for (auto c : s)
			r ^= c;
		return r;
	}

	char findTheDifference(string s, string t)
	{
		auto sx = xorChars(s);
		auto tx = xorChars(t);
		return sx ^ tx;
	}
};

int main()
{
	cout << Solution().findTheDifference("abcd", "abcde") << endl; // e

    return 0;
}

