CCFLAGS = -Wall -std=c++11
CC = g++

AddAndSearchWordDataStructureDesign:
	$(CC) $(CCFLAGS) AddAndSearchWordDataStructureDesign.cpp -o AddAndSearchWordDataStructureDesign
run: AddAndSearchWordDataStructureDesign
	./AddAndSearchWordDataStructureDesign
clean:
	rm AddAndSearchWordDataStructureDesign